apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-practice
spec:
  selector:
    matchLabels:
      app: demo-deployment
  replicas: 4
  template:
    metadata:
      labels:
        app: demo-deployment

    spec:
      containers:
        - name: demo-deployment-container
          image: nginx
          ports:
            - containerPort: 80
